apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rabbitmq-ns
  name: rabbitmq-pvc
  labels:
    app: rabbitmq
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---